package com.mineclawd.kubejs;

import com.mineclawd.MineClawd;
import dev.architectury.platform.Platform;
import net.minecraft.server.MinecraftServer;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

public final class KubeJsScriptManager {
    private static final String SCRIPT_FILE_NAME = "mineclawd-internal-api.js";
    private static final String SCRIPT_VERSION = "1.5.1-debug-20260226c";
    private static final String SCRIPT_CONTENT = String.join("\n",
            "// Generated by MineClawd. Do not edit.",
            "// Internal API version: " + SCRIPT_VERSION,
            "let TextClass = null;",
            "try { TextClass = Java.loadClass('net.minecraft.network.chat.Component'); } catch (e) {}",
            "if (TextClass == null) {",
            "  try { TextClass = Java.loadClass('net.minecraft.text.Text'); } catch (e) {}",
            "}",
            "",
            "const StringArgumentType = Java.loadClass('com.mojang.brigadier.arguments.StringArgumentType');",
            "const Base64Class = Java.loadClass('java.util.Base64');",
            "const JavaString = Java.loadClass('java.lang.String');",
            "let MineClawdBridge = null;",
            "try { MineClawdBridge = Java.loadClass('com.mineclawd.kubejs.KubeJsAgentBridge'); } catch (e) {",
            "  try { console.info('[MineClawd Debug][KubeJS] Failed to load KubeJS agent bridge: ' + String(e)); } catch (ignored) {}",
            "}",
            "",
            "function toText(message) {",
            "  if (TextClass == null) return String(message);",
            "  return TextClass.literal(String(message));",
            "}",
            "",
            "function sendOk(source, message) {",
            "  const text = toText(message);",
            "  if (source.sendFeedback) { source.sendFeedback(() => text, false); return; }",
            "  if (source.sendSuccess) { source.sendSuccess(text, false); return; }",
            "  if (source.sendMessage) { source.sendMessage(text); return; }",
            "}",
            "",
            "function sendErr(source, message) {",
            "  const text = toText(message);",
            "  if (source.sendError) { source.sendError(text); return; }",
            "  if (source.sendFailure) { source.sendFailure(text); return; }",
            "  if (source.sendMessage) { source.sendMessage(text); return; }",
            "}",
            "",
            "function decodeToolPayload(encoded) {",
            "  const encodedText = String(encoded == null ? '' : encoded);",
            "  if (MineClawdBridge != null) {",
            "    try {",
            "      return String(MineClawdBridge.decodeBase64UrlUtf8Any(encoded));",
            "    } catch (bridgeDecodeAnyErr) {",
            "      try {",
            "        return String(MineClawdBridge.decodeBase64UrlUtf8(encodedText));",
            "      } catch (bridgeDecodeErr) {",
            "      try { console.info('[MineClawd Debug][KubeJS] Bridge decode failed, falling back to JS decoder: ' + String(bridgeDecodeErr)); } catch (ignored) {}",
            "      }",
            "    }",
            "  }",
            "  const decoder = Base64Class.getUrlDecoder();",
            "  try {",
            "    const bytes = decoder.decode(encodedText);",
            "    try {",
            "      return String(new JavaString(bytes, 'UTF-8'));",
            "    } catch (utfErr) {",
            "      return String(new JavaString(bytes));",
            "    }",
            "  } catch (decodeStringErr) {",
            "    throw 'decode(String) failed: ' + String(decodeStringErr);",
            "  }",
            "}",
            "",
            "function resolveServerFromContext(context) {",
            "  if (context == null) {",
            "    try { if (typeof Utils !== 'undefined' && Utils.getServer) return Utils.getServer(); } catch (e) {}",
            "    return null;",
            "  }",
            "  try { if (context.getServer) return context.getServer(); } catch (e) {}",
            "  try { if (context.server) return context.server; } catch (e) {}",
            "  try { if (context.player && context.player.getServer) return context.player.getServer(); } catch (e) {}",
            "  try { if (context.source && context.source.getServer) return context.source.getServer(); } catch (e) {}",
            "  return null;",
            "}",
            "",
            "function resolveSourceFromContext(context, server) {",
            "  if (context != null) {",
            "    try { if (context.getSource) return context.getSource(); } catch (e) {}",
            "    try { if (context.source) return context.source; } catch (e) {}",
            "    try { if (context.player && context.player.getCommandSource) return context.player.getCommandSource().withMaxLevel(4); } catch (e) {}",
            "  }",
            "  try { if (server != null && server.getCommandSource) return server.getCommandSource().withMaxLevel(4); } catch (e) {}",
            "  return null;",
            "}",
            "",
            "const mineclawdApi = {};",
            "mineclawdApi.requestWithSession = function(player, sessionRef, request) {",
            "  if (MineClawdBridge == null) return 'ERROR: MineClawd bridge is unavailable.';",
            "  return MineClawdBridge.requestWithSession(",
            "    player,",
            "    String(sessionRef == null ? '' : sessionRef),",
            "    String(request == null ? '' : request)",
            "  );",
            "};",
            "mineclawdApi.requestOneShot = function(request, context) {",
            "  if (MineClawdBridge == null) return 'ERROR: MineClawd bridge is unavailable.';",
            "  let server = resolveServerFromContext(context);",
            "  if (server == null) {",
            "    try { if (typeof Utils !== 'undefined' && Utils.getServer) server = Utils.getServer(); } catch (e) {}",
            "  }",
            "  let source = resolveSourceFromContext(context, server);",
            "  return MineClawdBridge.requestOneShot(",
            "    source,",
            "    server,",
            "    String(request == null ? '' : request)",
            "  );",
            "};",
            "mineclawdApi.callWithSession = mineclawdApi.requestWithSession;",
            "mineclawdApi.callOneShot = mineclawdApi.requestOneShot;",
            "const mineclawd = mineclawdApi;",
            "",
            "console.info('[MineClawd] KubeJS bridge ready (internal api " + SCRIPT_VERSION + "): use `mineclawd.*` in this script context.');",
            "",
            "ServerEvents.commandRegistry(event => {",
            "  console.info('[MineClawd Debug][KubeJS] commandRegistry event fired (internal api " + SCRIPT_VERSION + ").');",
            "  const Commands = event.commands;",
            "  const Arguments = event.arguments;",
            "",
            "  event.register(",
            "    Commands.literal('_exec_kubejs_internal_mc')",
            "      .requires(source => source.hasPermission(2))",
            "      .then(Commands.argument('code', Arguments.GREEDY_STRING.create(event))",
            "        .executes(ctx => {",
            "          try {",
            "            let encoded = '';",
            "            try {",
            "              encoded = StringArgumentType.getString(ctx, 'code');",
            "            } catch (argErr) {",
            "              try {",
            "                encoded = ctx.getArgument('code', JavaString);",
            "              } catch (argErr2) {",
            "                sendErr(ctx.source, argErr2);",
            "                return 0;",
            "              }",
            "            }",
            "            if (encoded == null) encoded = '';",
            "            console.info('[MineClawd Debug][KubeJS] _exec_kubejs_internal_mc invoked; encoded_len=' + String(String(encoded).length) + ' encoded_type=' + String(typeof encoded) + ' bridge_loaded=' + String(MineClawdBridge != null));",
            "            let code = '';",
            "            try {",
            "              code = decodeToolPayload(encoded);",
            "            } catch (decodeErr) {",
            "              try { console.info('[MineClawd Debug][KubeJS] Payload decode failed: ' + String(decodeErr)); } catch (ignored) {}",
            "              sendErr(ctx.source, 'Failed to decode tool payload: ' + String(decodeErr));",
            "              return 0;",
            "            }",
            "            code = String(code);",
            "            console.info('[MineClawd Debug][KubeJS] Decoded instant script chars=' + String(code.length));",
            "            let source = ctx.source;",
            "            let server = null;",
            "            try {",
            "              if (typeof Utils !== 'undefined' && Utils.getServer) server = Utils.getServer();",
            "            } catch (e) {}",
            "            if (server == null) {",
            "              try {",
            "                if (source.getServer) server = source.getServer();",
            "                else if (source.server) server = source.server;",
            "              } catch (e) {}",
            "            }",
            "            let level = null;",
            "            try {",
            "              if (source.getLevel) level = source.getLevel();",
            "              else if (source.level) level = source.level;",
            "            } catch (e) {}",
            "            let player = null;",
            "            try {",
            "              if (source.player) player = source.player;",
            "              else if (source.getPlayer) player = source.getPlayer();",
            "              else if (source.getPlayerOrException) player = source.getPlayerOrException();",
            "            } catch (e) {}",
            "            let result = eval(code);",
            "            if (result === undefined) result = 'undefined';",
            "            sendOk(ctx.source, result);",
            "            return 1;",
            "          } catch (err) {",
            "            let details = '';",
            "            try { details = String(err); } catch (ignored) { details = 'Unknown JS error'; }",
            "            try { if (err != null && err.stack) details += '\\n' + String(err.stack); } catch (ignored) {}",
            "            try { if (err != null && err.javaException) details += '\\n' + String(err.javaException); } catch (ignored) {}",
            "            try { console.info('[MineClawd Debug][KubeJS] _exec_kubejs_internal_mc error: ' + details); } catch (ignored) {}",
            "            sendErr(ctx.source, details);",
            "            return 0;",
            "          }",
            "        })",
            "      )",
            "  );",
            "  console.info('[MineClawd Debug][KubeJS] Registered command `_exec_kubejs_internal_mc`.');",
            "});"
    );

    private KubeJsScriptManager() {
    }

    public static Path getScriptPath(Path runDir) {
        return runDir.resolve("kubejs").resolve("server_scripts").resolve(SCRIPT_FILE_NAME);
    }

    public static Path getScriptPath(MinecraftServer server) {
        Path runDir = server.getRunDirectory().toPath();
        return getScriptPath(runDir);
    }

    public static boolean ensureScriptInGameDir() {
        Path gameDir = Platform.getGameFolder();
        return ensureScript(gameDir);
    }

    public static boolean ensureScript(MinecraftServer server) {
        if (server == null) {
            return false;
        }
        return ensureScript(server.getRunDirectory().toPath());
    }

    public static boolean ensureScript(Path runDir) {
        if (runDir == null) {
            return false;
        }
        Path scriptPath = getScriptPath(runDir);
        try {
            Files.createDirectories(scriptPath.getParent());
            MineClawd.LOGGER.info("[MineClawd Debug][KubeJS] ensureScript start: runDir={} scriptPath={} version={}",
                    runDir, scriptPath, SCRIPT_VERSION);
            if (Files.exists(scriptPath)) {
                String existing = Files.readString(scriptPath);
                if (SCRIPT_CONTENT.equals(existing)) {
                    MineClawd.LOGGER.info("[MineClawd Debug][KubeJS] ensureScript up-to-date: {}", scriptPath);
                    return false;
                }
                MineClawd.LOGGER.info("[MineClawd Debug][KubeJS] ensureScript updating existing script: {} (existingChars={}, newChars={})",
                        scriptPath, existing.length(), SCRIPT_CONTENT.length());
            } else {
                MineClawd.LOGGER.info("[MineClawd Debug][KubeJS] ensureScript creating new script: {}",
                        scriptPath);
            }
            Files.writeString(scriptPath, SCRIPT_CONTENT, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
            MineClawd.LOGGER.info("[MineClawd Debug][KubeJS] ensureScript wrote script successfully: {}", scriptPath);
            return true;
        } catch (IOException e) {
            MineClawd.LOGGER.error("Failed to create KubeJS internal script at {}", scriptPath, e);
            return false;
        }
    }
}
